import type { BoardColumn, BoardRow, SavedView } from "@/components/board-workspace";
import type { Benefit } from "@/data/types";
import { getBenefitPercent, getBenefitRealised, getNextMeasurementDue, getProject, getProgramme, getStrategicObjectives } from "@/services/pmo";
export const benefitColumns:BoardColumn[]=[{key:"reference",label:"Reference",type:"text",width:110},{key:"title",label:"Benefit",type:"text",summary:"count",width:280},{key:"type",label:"Type",type:"status",editable:true,options:["Benefit","Disbenefit"]},{key:"classification",label:"Classification",type:"status"},{key:"people",label:"Benefit owner",type:"people"},{key:"projects",label:"Enabling projects",type:"tags",width:260},{key:"planned",label:"Planned total value",type:"number",unit:"currency",summary:"sum"},{key:"realised",label:"Realised to date",type:"number",unit:"currency",summary:"sum"},{key:"progress",label:"% realised",type:"progress",summary:"average",unit:"%"},{key:"confidence",label:"Confidence",type:"status"},{key:"finish",label:"Next measurement due",type:"date"},{key:"status",label:"Status",type:"status"}];
export const benefitsToRows=(items:Benefit[]):BoardRow[]=>items.map(item=>{const projectLinks=item.enablingProjects.map(link=>getProject(link.projectId)).filter(Boolean),programmeNames=Array.from(new Set(projectLinks.map(project=>getProgramme(project?.programmeId??"")?.name??"Unassigned"))),objectives=item.strategicObjectiveIds.map(id=>getStrategicObjectives().find(objective=>objective.id===id)?.title??id);return{id:item.id,reference:item.reference,title:item.title,type:item.type,classification:item.classification,people:item.owner?[item.owner]:[],owner:item.owner,projects:projectLinks.map(project=>project?.name??"Unknown"),programme:programmeNames.join(", "),objective:objectives.join(", "),planned:item.plannedTotalValue,realised:getBenefitRealised(item),progress:getBenefitPercent(item),confidence:item.confidence,finish:getNextMeasurementDue(item),status:item.status,measurementOverdue:item.measures.some(measure=>measure.nextDue<"21/09/2026"),unownedOrUnvalidated:!item.owner||!item.eligibilityConfirmed,closedProjectRealisation:item.status==="In realisation"&&projectLinks.some(project=>project?.state==="Closed"),disbenefit:item.type==="Disbenefit",group:objectives[0]??"Unaligned"}});
const visible=benefitColumns.map(column=>column.key);
export const benefitViews:SavedView[]=[
 {id:"all",name:"All benefits",type:"table",groupBy:"",sortKey:"reference",filter:"",visible,isDefault:true},
 {id:"objective",name:"By strategic objective",type:"table",groupBy:"objective",sortKey:"reference",filter:"",visible,isDefault:false},
 {id:"programme",name:"By programme",type:"table",groupBy:"programme",sortKey:"reference",filter:"",visible,isDefault:false},
 {id:"cash",name:"Cash-releasing",type:"table",groupBy:"",sortKey:"reference",filter:"",filters:[{key:"classification",operator:"equals",value:"Cash-releasing"}],visible,isDefault:false},
 {id:"disbenefits",name:"Disbenefits",type:"table",groupBy:"",sortKey:"reference",filter:"",filters:[{key:"type",operator:"equals",value:"Disbenefit"}],visible,isDefault:false},
 {id:"overdue",name:"Measurements overdue",type:"table",groupBy:"",sortKey:"finish",filter:"",filters:[{key:"measurementOverdue",operator:"truthy"}],visible,isDefault:false},
 {id:"unowned",name:"Unowned or unvalidated",type:"table",groupBy:"",sortKey:"reference",filter:"",filters:[{key:"unownedOrUnvalidated",operator:"truthy"}],visible,isDefault:false},
 {id:"closed",name:"In realisation (closed projects)",type:"table",groupBy:"",sortKey:"reference",filter:"",filters:[{key:"closedProjectRealisation",operator:"truthy"}],visible,isDefault:false},
];