import { createFileRoute, Link } from "@tanstack/react-router";
import { TriangleAlert } from "lucide-react";
import { BenefitsNav } from "@/components/benefits-nav";
import { BoardWorkspace } from "@/components/board-workspace";
import { PageHeader, KpiCard } from "@/components/pmo-ui";
import { benefitColumns, benefitsToRows, benefitViews } from "@/lib/benefit-board-data";
import { getBenefitMetrics, getBenefitWarnings, getBenefits } from "@/services/pmo";
export const Route=createFileRoute("/benefits/")({head:()=>({meta:[{title:"Benefits Register — Virtual PMO"},{name:"description",content:"Portfolio benefits, disbenefits, ownership and realisation evidence."},{property:"og:title",content:"Benefits Register — Virtual PMO"},{property:"og:description",content:"Portfolio benefits, disbenefits, ownership and realisation evidence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BenefitsRegister});
function money(value:number){return `£${Math.round(value/1000)}k`}
function BenefitsRegister(){const benefits=getBenefits(),metrics=getBenefitMetrics(),warnings=getBenefitWarnings();return <div className="space-y-7"><PageHeader eyebrow="Benefits management" title="Benefits Register" description="Own, evidence and realise portfolio outcomes using MSP and Green Book-aligned controls."/><BenefitsNav/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="Benefits" value={String(benefits.filter(item=>item.type==="Benefit").length)} detail="Across nine projects" icon="projects"/><KpiCard label="Disbenefits" value={String(benefits.filter(item=>item.type==="Disbenefit").length)} detail="Explicitly monitored" icon="health"/><KpiCard label="Planned value" value={money(metrics.planned)} detail="Quantified portfolio value" icon="budget"/><KpiCard label="Realised" value={`${metrics.percent}%`} detail={money(metrics.realised)} icon="forecast"/><KpiCard label="Measurements overdue" value={String(metrics.overdue)} detail="Require evidence" icon="health"/></div>{warnings.length>0&&<div className="flex gap-3 rounded-md border border-health-warn/40 bg-health-warn/10 p-4"><TriangleAlert className="size-5 shrink-0 text-health-warn-foreground"/><div><p className="text-sm font-semibold">Assurance warnings</p>{warnings.map(item=><p key={item} className="mt-1 text-xs text-muted-foreground">{item}</p>)}</div></div>}<BoardWorkspace title="Benefits register" rows={benefitsToRows(benefits)} columns={benefitColumns} groupOptions={["objective","programme","classification","status","confidence"]} seededViews={benefitViews} renderTitle={row=><Link to="/benefits/$benefitId" params={{benefitId:row.id}} className="text-primary hover:underline">{Boolean(row["disbenefit"])&&<span className="mr-2 text-health-bad">●</span>}{row.title}</Link>}/></div>}