import { createFileRoute, Link } from "@tanstack/react-router";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip } from "recharts";
import { BoardWorkspace, type BoardColumn, type BoardRow } from "@/components/board-workspace";
import { KpiCard, PageHeader } from "@/components/pmo-ui";
import { getPortfolio, getPortfolioHealth, getPortfolioMetrics, getProgrammeHealth, getProgrammeMetrics, getProgrammes } from "@/services/pmo";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Portfolio Overview — Virtual PMO"},{name:"description",content:"DTS portfolio health, delivery and financial overview."},{property:"og:title",content:"Portfolio Overview — Virtual PMO"},{property:"og:description",content:"DTS portfolio health, delivery and financial overview."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:PortfolioPage});
const money=(value:number)=>`£${(value/1_000_000).toFixed(1)}M`;
const columns:BoardColumn[]=[{key:"title",label:"Programme",type:"text",summary:"count",width:300},{key:"status",label:"Health",type:"status",summary:"rag"},{key:"people",label:"Manager",type:"people"},{key:"number",label:"Projects",type:"number",summary:"sum"},{key:"budget",label:"Budget",type:"number",summary:"sum"},{key:"forecast",label:"Forecast",type:"number",summary:"sum"},{key:"formula",label:"RAG mix",type:"formula"}];
function PortfolioPage(){const portfolio=getPortfolio(),metrics=getPortfolioMetrics(),programmes=getProgrammes();const chart=[{name:"On Track",value:metrics.rag.green,fill:"var(--health-good)"},{name:"At Risk",value:metrics.rag.amber,fill:"var(--health-warn)"},{name:"Off Track",value:metrics.rag.red,fill:"var(--health-bad)"}];const rows:BoardRow[]=programmes.map(programme=>{const m=getProgrammeMetrics(programme);return{id:programme.id,title:programme.name,status:getProgrammeHealth(programme),people:[programme.manager],number:m.projectCount,budget:m.budget,forecast:m.forecast,formula:`${m.rag.green} green · ${m.rag.amber} amber · ${m.rag.red} red`,group:getProgrammeHealth(programme)}});return <div className="space-y-8"><PageHeader eyebrow="Portfolio" title={portfolio.name} description={portfolio.description} actions={<span className="rounded bg-accent px-3 py-2 text-sm font-semibold">{getPortfolioHealth()}</span>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Active projects" value={String(metrics.activeProjects)} detail="Across five programmes" icon="projects"/><KpiCard label="Total project budget" value={money(metrics.totalBudget)} detail="Approved delivery budget" icon="budget"/><KpiCard label="Forecast" value={money(metrics.forecast)} detail={`${money(metrics.forecast-metrics.totalBudget)} variance`} icon="forecast"/><KpiCard label="Projects on track" value={`${metrics.percentOnTrack}%`} detail={`${metrics.rag.green} of 25 projects`} icon="health"/></div><div className="grid gap-6 xl:grid-cols-[320px_1fr]"><section className="rounded-md border bg-card p-5 shadow-sm"><h2 className="font-display text-lg font-semibold">Portfolio health</h2><div className="h-56"><ResponsiveContainer><PieChart><Pie data={chart} dataKey="value" innerRadius={58} outerRadius={84}>{chart.map(item=><Cell key={item.name} fill={item.fill}/>)}</Pie><ChartTooltip/></PieChart></ResponsiveContainer></div></section><section><h2 className="mb-4 font-display text-lg font-semibold">Programmes</h2><BoardWorkspace title="Programmes" rows={rows} columns={columns} groupOptions={["group","status"]} renderTitle={row=><Link to="/programmes/$programmeId" params={{programmeId:row.id}} className="text-primary hover:underline">{row.title}</Link>}/></section></div></div>}
