import { AutoBreadcrumbs } from "@/components/section-nav";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { BarChart3, CalendarRange, Gauge, GripVertical, LayoutDashboard, ListChecks, Plus, Table2, UsersRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/pmo-ui";
import { getPortfolioMetrics, getProjects } from "@/services/pmo";
import { cn } from "@/lib/utils";
export const Route=createFileRoute("/insights/dashboards")({head:()=>({meta:[{title:"DTS Portfolio Dashboard — Virtual PMO"},{name:"description",content:"Custom portfolio dashboard with delivery, risk, finance and workload widgets."},{property:"og:title",content:"DTS Portfolio Dashboard — Virtual PMO"},{property:"og:description",content:"Custom portfolio dashboard with delivery, risk, finance and workload widgets."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DashboardPage});
type Widget="KPI number"|"RAG donut"|"Bar chart"|"Table"|"Timeline"|"Milestone list"|"Workload";const all:Widget[]=["KPI number","RAG donut","Bar chart","Table","Timeline","Milestone list","Workload"];
function DashboardPage(){const [widgets,setWidgets]=useState<Widget[]>(all),[picker,setPicker]=useState(false),[dragged,setDragged]=useState<number|null>(null);return <div className="space-y-6"><AutoBreadcrumbs/><PageHeader eyebrow="Dashboard" title="DTS Portfolio" description="A configurable view of delivery, finance, milestones and portfolio capacity." actions={<Button onClick={()=>setPicker(true)}><Plus/>Add widget</Button>}/><div className="grid auto-rows-[260px] gap-4 lg:grid-cols-2 xl:grid-cols-3">{widgets.map((widget,index)=><section key={`${widget}-${index}`} draggable onDragStart={()=>setDragged(index)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(dragged===null||dragged===index)return;const next=[...widgets],moved=next.splice(dragged,1)[0];if(moved)next.splice(index,0,moved);setWidgets(next);setDragged(null)}} className={cn("overflow-hidden rounded-md border bg-card p-5 shadow-sm",(widget==="Table"||widget==="Timeline")&&"lg:col-span-2",dragged===index&&"opacity-50")}><header className="mb-4 flex items-center gap-2"><GripVertical className="size-4 cursor-grab text-muted-foreground"/><WidgetIcon type={widget}/><h2 className="font-semibold">{widget}</h2><Button variant="ghost" size="icon" className="ml-auto" onClick={()=>setWidgets(current=>current.filter((_,i)=>i!==index))}><X/></Button></header><WidgetBody type={widget}/></section>)}</div>{picker&&<div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4"><div role="dialog" className="w-full max-w-lg rounded-md border bg-background p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-semibold">Widget picker</h2><Button size="icon" variant="ghost" onClick={()=>setPicker(false)}><X/></Button></div><div className="mt-5 grid grid-cols-2 gap-3">{all.map(type=><Button key={type} variant="outline" className="h-20 justify-start" onClick={()=>{setWidgets(current=>[...current,type]);setPicker(false)}}><WidgetIcon type={type}/>{type}</Button>)}</div></div></div>}</div>}
function WidgetIcon({type}:{type:Widget}){const Icon=type==="KPI number"?Gauge:type==="RAG donut"?LayoutDashboard:type==="Bar chart"?BarChart3:type==="Table"?Table2:type==="Timeline"?CalendarRange:type==="Milestone list"?ListChecks:UsersRound;return <Icon className="size-4 text-primary"/>}
 function WidgetBody({type}:{type:Widget}){const metrics=getPortfolioMetrics(),projects=getProjects();if(type==="KPI number")return <><p className="text-5xl font-semibold">{metrics.activeProjects}</p><p className="mt-3 text-sm text-muted-foreground">Active projects across five programmes</p></>;if(type==="RAG donut"){const data=[{name:"On Track",value:metrics.rag.green,fill:"var(--health-good)"},{name:"At Risk",value:metrics.rag.amber,fill:"var(--health-warn)"},{name:"Off Track",value:metrics.rag.red,fill:"var(--health-bad)"}];return <ResponsiveContainer width="100%" height="80%"><PieChart><Pie data={data} dataKey="value" innerRadius={48} outerRadius={74}>{data.map(item=><Cell key={item.name} fill={item.fill}/>)}</Pie></PieChart></ResponsiveContainer>}if(type==="Bar chart")return <ResponsiveContainer width="100%" height="80%"><BarChart data={[{name:"Budget",value:metrics.totalBudget/1e6},{name:"Forecast",value:metrics.forecast/1e6}]}><XAxis dataKey="name"/><YAxis/><Bar dataKey="value" fill="var(--primary)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>;if(type==="Table")return <div className="divide-y">{projects.slice(0,4).map(project=><div key={project.id} className="flex justify-between py-2 text-sm"><span>{project.name}</span><strong>{project.stage}</strong></div>)}</div>;if(type==="Timeline")return <div className="space-y-4">{projects.slice(0,4).map((project,index)=><div key={project.id} className="grid grid-cols-[180px_1fr] items-center text-xs"><span className="truncate">{project.name}</span><div className="h-3 bg-muted"><div className="h-full bg-primary" style={{marginLeft:`${index*8}%`,width:`${35-index*3}%`}}/></div></div>)}</div>;if(type==="Milestone list")return <div className="space-y-3">{projects.slice(0,4).map(project=><div key={project.id} className="flex gap-2 text-sm"><span className="text-primary">◆</span><span>{project.milestones[0]?.title}</span><span className="ml-auto text-muted-foreground">{project.milestones[0]?.forecastDate}</span></div>)}</div>;return <div className="space-y-3">{["Freya Walsh","George Clarke","Maya Harrison","Jacob Cole"].map((name,index)=><div key={name}><div className="flex justify-between text-xs"><span>{name}</span><span>{28+index*5}h</span></div><div className="mt-1 h-2 bg-muted"><div className={cn("h-full",index>1?"bg-health-bad":"bg-primary")} style={{width:`${70+index*8}%`}}/></div></div>)}</div>}
