import { AutoBreadcrumbs } from "@/components/section-nav";
import { formatCompactCurrency } from "@/lib/format";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Landmark, Layers3, WalletCards } from "lucide-react";
import { PageHeader } from "@/components/pmo-ui";
import { getCollectionMetrics, getCollections } from "@/services/pmo";

export const Route=createFileRoute("/portfolio/collections/")({head:()=>({meta:[{title:"Collections — Virtual PMO"},{name:"description",content:"Cross-cutting governance, priority and funding views."},{property:"og:title",content:"Collections — Virtual PMO"},{property:"og:description",content:"Cross-cutting governance, priority and funding views."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:CollectionsPage});
const icons={Governance:Landmark,"Priority set":Layers3,"Funding stream":WalletCards};
const money = formatCompactCurrency;
function CollectionsPage(){return <div className="space-y-8"><AutoBreadcrumbs/><PageHeader title="Collections" description="Cross-cutting views for governance, strategic priorities and funding streams."/><div className="grid gap-4 lg:grid-cols-3">{getCollections().map(collection=>{const metrics=getCollectionMetrics(collection.id),Icon=icons[collection.type];return <Link key={collection.id} to="/portfolio/collections/$collectionId" params={{collectionId:collection.id}} className="group rounded-lg border border-border bg-card p-5 shadow-sm transition hover:border-primary/40 hover:shadow-md"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-md bg-accent text-accent-foreground"><Icon className="size-5"/></span><ArrowRight className="size-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-primary"/></div><p className="mt-5 text-xs font-semibold uppercase text-primary">{collection.type}</p><h2 className="mt-1 font-display text-xl font-semibold">{collection.name}</h2><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4 text-sm"><div><p className="text-xs text-muted-foreground">Projects</p><p className="mt-1 font-semibold">{metrics.projectCount}</p></div><div><p className="text-xs text-muted-foreground">Budget</p><p className="mt-1 font-semibold">{collection.potAmount?money(collection.potAmount):money(metrics.budget)}</p></div></div></Link>})}</div></div>}