import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CalendarDays, CheckCircle2, Circle, ExternalLink, ListChecks, Milestone, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { HealthPill } from "@/components/health-pill";
import { Fact, KpiCard } from "@/components/pmo-ui";
import { getEffortHealth, getFinancialHealth, getIssueHealth, getProgramme, getProject, getProjectHealth, getProjectTeam, getScheduleHealth } from "@/services/pmo";
import type { ProjectStage } from "@/data/types";
import { TaskWorkspace } from "@/components/task-workspace";
import { StatusWorkspace } from "@/components/status-workspace";
import { ProjectResources } from "@/components/project-resources";
import { RaidWorkspace } from "@/components/raid-workspace";

export const Route=createFileRoute("/projects/$projectId")({head:({params})=>{const p=getProject(params.projectId);const title=p?`${p.name} — Virtual PMO`:"Project — Virtual PMO";const description=p?.businessCase??"Project detail.";return{meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}},component:ProjectPage});
const stages:ProjectStage[]=["Discover","Define","Plan","Deliver","Close"];
const money=(value:number)=>value>=1_000_000?`£${(value/1_000_000).toFixed(1)}M`:`£${Math.round(value/1_000)}k`;
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border border-border bg-card p-5 shadow-sm"><h2 className="font-display text-lg font-semibold">{title}</h2>{children}</section>}
function ProjectPage(){const {projectId}=Route.useParams();const project=getProject(projectId);const [tab,setTab]=useState("overview");if(!project)return <p>Project not found.</p>;const programme=getProgramme(project.programmeId),current=stages.indexOf(project.stage),reports=project.reports??[],tasks=project.tasks??[],team=getProjectTeam(project),changes=project.changes??[];const tabs=["overview","status","tasks","resources","raid","changes","financials","business case"];
 return <div className="space-y-7"><header className="border-b border-border pb-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-primary">{programme?.name}</p><h1 className="font-display text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-sm text-muted-foreground">{project.businessCase}</p></div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex h-8 items-center gap-1.5 rounded-md bg-accent px-3 text-xs font-semibold text-accent-foreground"><ListChecks className="size-4"/>{project.taskSource}</span><Button variant="outline" size="sm"><ExternalLink/>Open in Planner</Button><span className="text-xs text-muted-foreground">Last synced 2 mins ago</span></div></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.35fr_1fr]"><div><p className="mb-3 text-xs font-semibold text-muted-foreground">Stage</p><div className="flex items-center">{stages.map((stage,index)=><div key={stage} className="flex min-w-0 flex-1 items-center last:flex-none"><div className="flex flex-col items-center gap-1.5"><span className={`grid size-7 place-items-center rounded-full border ${index<current?"border-primary bg-primary text-primary-foreground":index===current?"border-primary bg-accent text-primary":"border-border bg-card text-muted-foreground"}`}>{index<current?<CheckCircle2 className="size-4"/>:<Circle className="size-3"/>}</span><span className={`text-[10px] ${index===current?"font-semibold text-primary":"text-muted-foreground"}`}>{stage}</span></div>{index<stages.length-1&&<div className={`mb-5 h-px flex-1 ${index<current?"bg-primary":"bg-border"}`}/>}</div>)}</div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Fact label="Project manager" value={project.manager}/><Fact label="Sponsor" value={project.sponsor}/><Fact label="Priority" value={project.priority}/><Fact label="Finish" value={project.finish}/></div></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><div className="flex items-center justify-between rounded-md bg-muted/60 px-3 py-2"><span className="text-xs text-muted-foreground">Overall</span><HealthPill health={getProjectHealth(project)}/></div><div className="flex items-center justify-between rounded-md bg-muted/60 px-3 py-2"><span className="text-xs text-muted-foreground">Schedule</span><HealthPill health={getScheduleHealth(project)}/></div><div className="flex items-center justify-between rounded-md bg-muted/60 px-3 py-2"><span className="text-xs text-muted-foreground">Issues & risks</span><HealthPill health={getIssueHealth(project)}/></div></div></header><div className="flex overflow-x-auto border-b border-border">{tabs.map(item=><Button key={item} variant="ghost" onClick={()=>setTab(item)} className={tab===item?"rounded-none border-b-2 border-primary text-primary":"rounded-none text-muted-foreground"}>{item[0]?.toUpperCase()}{item.slice(1)}</Button>)}</div>
 {tab==="overview"&&<div className="grid gap-5 xl:grid-cols-12"><div className="space-y-5 xl:col-span-8"><div className="grid gap-4 sm:grid-cols-3"><KpiCard label="Budget" value={money(project.budget)} detail={`${money(project.actual)} actual`} icon="budget"/><KpiCard label="Forecast" value={money(project.forecast)} detail={`${money(project.forecast-project.budget)} variance`} icon="forecast"/><KpiCard label="Task progress" value={`${Math.round(tasks.reduce((s,t)=>s+t.percentComplete,0)/(tasks.length||1))}%`} detail={`${tasks.filter(t=>t.percentComplete===100).length} of ${tasks.length} complete`} icon="projects"/></div><Section title="Delivery timeline"><div className="mt-5 flex items-center gap-3"><CalendarDays className="size-5 text-primary"/><div className="flex-1"><div className="h-2 rounded-full bg-muted"><div className="h-full w-[44%] rounded-full bg-primary"/></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{project.start}</span><span>21/09/2026</span><span>{project.finish}</span></div></div></div></Section><Section title="Latest status report">{reports[0]?<div className="mt-4"><div className="flex flex-wrap items-center gap-3"><HealthPill health={reports[0].overall}/><span className="text-xs text-muted-foreground">{reports[0].reportingDate} · {reports[0].submitter}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-semibold">Accomplished</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{reports[0].accomplished}</p></div><div><p className="text-xs font-semibold">Planned next</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{reports[0].planned}</p></div></div></div>:<p className="mt-3 text-sm text-muted-foreground">No report submitted.</p>}</Section></div><div className="space-y-5 xl:col-span-4"><Section title="Top risks"><div className="mt-4 space-y-3">{project.risks.slice(0,3).map(r=><div key={r.id} className="rounded-md border border-border p-3"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{r.title}</p><span className="rounded bg-health-warn/20 px-2 py-0.5 text-xs font-semibold text-health-warn-foreground">{r.score}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{r.description}</p></div>)}</div></Section><Section title="Upcoming milestones"><div className="mt-4 space-y-4">{tasks.filter(t=>t.isMilestone).map(t=><div key={t.id} className="flex gap-3"><Milestone className="mt-0.5 size-4 text-primary"/><div><p className="text-sm font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{t.finish}</p></div></div>)}</div></Section></div></div>}
  {tab==="status"&&<StatusWorkspace project={project} initialReports={reports} calculated={{overall:getProjectHealth(project),schedule:getScheduleHealth(project),financial:getFinancialHealth(project),effort:getEffortHealth(project),issue:getIssueHealth(project)}}/>}{tab==="tasks"&&<TaskWorkspace initialTasks={tasks} taskSource={project.taskSource}/>} {tab==="resources"&&<ProjectResources members={team}/>} {tab==="raid"&&<RaidWorkspace risks={project.risks} issues={project.issues}/>} {tab==="changes"&&<Section title="Change requests"><div className="mt-4 space-y-3">{changes.map(c=><div key={c.id} className="flex items-center justify-between border-b border-border py-3"><div><p className="text-sm font-medium">{c.title}</p><p className="text-xs text-muted-foreground">{c.type} · {c.scheduleImpactDays} days</p></div><span className="text-sm">{c.status}</span></div>)}</div></Section>}{tab==="financials"&&<div className="grid gap-4 md:grid-cols-3"><KpiCard label="Budget" value={money(project.budget)} detail="Approved baseline" icon="budget"/><KpiCard label="Actual" value={money(project.actual)} detail="Spend to date" icon="budget"/><KpiCard label="Forecast" value={money(project.forecast)} detail={`${money(project.forecast-project.budget)} variance`} icon="forecast"/></div>}{tab==="business case"&&<div className="grid gap-5 lg:grid-cols-2"><Section title="Summary"><p className="mt-3 text-sm leading-7 text-muted-foreground">{project.businessCase}</p></Section><Section title="Expected benefits"><p className="mt-3 text-sm leading-7 text-muted-foreground">{project.benefits}</p></Section></div>}</div>}