import { createFileRoute } from "@tanstack/react-router";
import { BoardWorkspace, type BoardColumn, type BoardRow } from "@/components/board-workspace";
import { PageHeader } from "@/components/pmo-ui";
export const Route=createFileRoute("/requests")({head:()=>({meta:[{title:"Requests — Virtual PMO"},{name:"description",content:"Review, score and progress project requests."},{property:"og:title",content:"Requests — Virtual PMO"},{property:"og:description",content:"Review, score and progress project requests."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:RequestsPage});
const rows:BoardRow[]=[
{id:"req1",title:"Student mobile app refresh",status:"In Review",people:["Maya Harrison"],sponsor:"Priya Nair",number:180000,benefit:420000,priority:"High",alignment:88,formula:"82",group:"In Review",tags:["Student experience"]},
{id:"req2",title:"Research storage expansion",status:"New",people:["Jacob Cole"],sponsor:"Daniel Mercer",number:240000,benefit:310000,priority:"Critical",alignment:91,formula:"86",group:"New",tags:["Research"]},
{id:"req3",title:"Digital assessment pilot",status:"Approved",people:["Eva Chen"],sponsor:"Rachel King",number:95000,benefit:260000,priority:"High",alignment:84,formula:"79",group:"Approved",tags:["Teaching"]},
{id:"req4",title:"Legacy telephony retirement",status:"On Hold",people:["George Clarke"],sponsor:"Martin Lowe",number:130000,benefit:190000,priority:"Moderate",alignment:67,formula:"63",group:"On Hold",tags:["Efficiency"]},
{id:"req5",title:"AI meeting assistant",status:"Rejected",people:["Layla Owen"],sponsor:"Priya Nair",number:60000,benefit:85000,priority:"Low",alignment:51,formula:"48",group:"Rejected",tags:["AI"]},
{id:"req6",title:"Identity proofing service",status:"In Review",people:["Harrison Shaw"],sponsor:"Aisha Wallace",number:210000,benefit:380000,priority:"Critical",alignment:93,formula:"89",group:"In Review",tags:["Security"]},
];
const columns:BoardColumn[]=[{key:"title",label:"Request",type:"text",editable:true,summary:"count",width:280},{key:"status",label:"State",type:"status",editable:true,options:["New","In Review","On Hold","Approved","Rejected"]},{key:"people",label:"Requester",type:"people",editable:true},{key:"sponsor",label:"Sponsor",type:"text",editable:true},{key:"number",label:"Estimated cost",type:"number",summary:"sum"},{key:"benefit",label:"Estimated benefit",type:"number",summary:"sum"},{key:"alignment",label:"Strategic alignment",type:"progress",summary:"average"},{key:"priority",label:"Priority",type:"priority",editable:true,options:["Low","Moderate","High","Critical"]},{key:"tags",label:"Themes",type:"tags"},{key:"formula",label:"Priority score",type:"formula"}];
function RequestsPage(){return <div className="space-y-7"><PageHeader eyebrow="Portfolio intake" title="Requests" description="Review, prioritise and progress new project proposals through a transparent pipeline."/><BoardWorkspace title="Requests" rows={rows} columns={columns} groupOptions={["group","priority","sponsor"]} initialView="kanban"/></div>}
