import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { AlertTriangle, ShieldAlert } from "lucide-react";
import { PageHeader } from "@/components/pmo-ui";
import { RaidWorkspace } from "@/components/raid-workspace";
import { Button } from "@/components/ui/button";
import { getPortfolioRisks } from "@/services/pmo";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/risks")({head:()=>({meta:[{title:"Portfolio Risks — Virtual PMO"},{name:"description",content:"Portfolio-wide risk exposure, heat map and project risk register."},{property:"og:title",content:"Portfolio Risks — Virtual PMO"},{property:"og:description",content:"Portfolio-wide risk exposure, heat map and project risk register."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:RisksPage});
function RisksPage(){const all=getPortfolioRisks();const [filter,setFilter]=useState<"All"|"Critical"|"Elevated"|"Low">("All");const [status,setStatus]=useState<"All"|"Open"|"Closed">("All");const visible=useMemo(()=>all.filter(r=>(status==="All"||r.status===status)&&(filter==="All"||(filter==="Critical"&&r.score>=15)||(filter==="Elevated"&&r.score>=8&&r.score<15)||(filter==="Low"&&r.score<8))),[all,filter,status]);return <div className="space-y-8"><PageHeader eyebrow="Portfolio assurance" title="Risks" description="Aggregated risk exposure across every programme and project."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Open risks" value={String(all.filter(r=>r.status==="Open").length)} icon="shield"/><Metric label="Critical" value={String(all.filter(r=>r.score>=15).length)} tone="bad"/><Metric label="Elevated" value={String(all.filter(r=>r.score>=8&&r.score<15).length)} tone="warn"/><Metric label="Due for review" value={String(all.filter(r=>r.reviewDate==="23/09/2026"||r.reviewDate==="30/09/2026").length)} icon="alert"/></div><div className="flex flex-wrap items-center gap-4"><div className="flex flex-wrap gap-2" aria-label="Risk severity filters">{(["All","Critical","Elevated","Low"] as const).map(value=><Button key={value} size="sm" variant={filter===value?"default":"outline"} onClick={()=>setFilter(value)}>{value}</Button>)}</div><span className="hidden h-6 w-px bg-border sm:block"/><label className="flex items-center gap-2 text-xs font-semibold text-muted-foreground">Status<select value={status} onChange={event=>setStatus(event.target.value as typeof status)} className="h-9 rounded-md border border-input bg-background px-3 text-sm font-medium text-foreground"><option>All</option><option>Open</option><option>Closed</option></select></label></div><RaidWorkspace risks={visible} issues={[]}/><section><h2 className="font-display text-xl font-semibold">Project links</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{visible.slice(0,12).map(risk=><Link key={`${risk.projectId}-${risk.id}`} to="/projects/$projectId" params={{projectId:risk.projectId}} className="rounded-md border border-border bg-card p-3 hover:bg-accent/40"><p className="text-sm font-semibold text-primary">{risk.projectName}</p><p className="mt-1 text-xs text-muted-foreground">{risk.programmeName}</p></Link>)}</div></section></div>}
function Metric({label,value,tone,icon}:{label:string;value:string;tone?:"bad"|"warn";icon?:"shield"|"alert"}){const Icon=icon==="alert"?AlertTriangle:ShieldAlert;return <div className={cn("rounded-lg border border-border bg-card p-5 shadow-sm",tone==="bad"&&"border-health-bad/40",tone==="warn"&&"border-health-warn/50")}><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className={cn("size-4 text-muted-foreground",tone==="bad"&&"text-health-bad-foreground",tone==="warn"&&"text-health-warn-foreground")}/></div><p className={cn("mt-4 text-3xl font-semibold",tone==="bad"&&"text-health-bad-foreground",tone==="warn"&&"text-health-warn-foreground")}>{value}</p></div>}