import { useState } from "react";
import { AlertTriangle, CircleDot } from "lucide-react";
import type { Issue, Risk } from "@/data/types";
import { BoardWorkspace } from "@/components/board-workspace";
import { issueColumns, issuesToRows, riskColumns, risksToRows } from "@/lib/board-data";
import { cn } from "@/lib/utils";
const band=(score:number)=>score>=15?"bg-health-bad/20 text-health-bad-foreground":score>=8?"bg-health-warn/25 text-health-warn-foreground":"bg-health-good/20 text-health-good-foreground";
export function RaidWorkspace({risks,issues}:{risks:Risk[];issues:Issue[]}){const [selected,setSelected]=useState<{probability:number;impact:number}|null>(null);const visible=selected?risks.filter(r=>r.probability===selected.probability&&r.impact===selected.impact):risks;return <div className="space-y-8"><section className="grid gap-6 xl:grid-cols-[430px_1fr]"><div><h2 className="font-display text-xl font-semibold">Risk heat map</h2><p className="mt-1 text-sm text-muted-foreground">Select a cell to filter the risk register.</p><div className="mt-5 grid grid-cols-[34px_repeat(5,minmax(0,1fr))] gap-1" aria-label="5 by 5 risk heat map"><div/><div className="col-span-5 text-center text-[11px] font-semibold text-muted-foreground">Impact →</div>{[5,4,3,2,1].map(probability=><div key={probability} className="contents"><div className="grid place-items-center text-xs font-semibold text-muted-foreground">{probability}</div>{[1,2,3,4,5].map(impact=>{const cell=risks.filter(r=>r.probability===probability&&r.impact===impact);const score=probability*impact;const active=selected?.probability===probability&&selected.impact===impact;return <button key={impact} type="button" onClick={()=>setSelected(active?null:{probability,impact})} aria-label={`Probability ${probability}, impact ${impact}, ${cell.length} risks`} className={cn("relative grid aspect-square place-items-center rounded-md border text-sm font-bold",band(score),active?"border-primary ring-2 ring-primary/30":"border-transparent")}><span>{cell.length||""}</span>{cell.length>0&&<CircleDot className="absolute right-1 top-1 size-3"/>}</button>})}</div>)}<div/>{[1,2,3,4,5].map(impact=><div key={impact} className="text-center text-xs font-semibold text-muted-foreground">{impact}</div>)}</div></div><div className="self-end rounded-md border bg-card p-5"><div className="flex gap-3"><AlertTriangle className="size-5 text-health-warn-foreground"/><p className="text-sm">{risks.filter(r=>r.score>=15).length} critical and {risks.filter(r=>r.score>=8&&r.score<15).length} elevated risks.</p></div>{selected&&<button className="mt-4 text-sm font-semibold text-primary" onClick={()=>setSelected(null)}>Clear cell filter</button>}</div></section><section><h2 className="mb-3 font-display text-xl font-semibold">Risk register</h2>{visible.length?<BoardWorkspace title="Risks" rows={risksToRows(visible)} columns={riskColumns} groupOptions={["group","formula","response"]}/>:<Empty text="No risks in this heat-map cell."/>}</section><section><h2 className="mb-3 font-display text-xl font-semibold">Issues</h2>{issues.length?<BoardWorkspace title="Issues" rows={issuesToRows(issues)} columns={issueColumns} groupOptions={["group","priority"]}/>:<Empty text="No open issues."/>}</section></div>}
function Empty({text}:{text:string}){return <div className="rounded-md border border-dashed py-10 text-center text-sm text-muted-foreground">{text}</div>}
