import { formatDate } from "@/lib/format";
import { useMemo, useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { QueryState } from "@/components/query-state";
import { useResourceData } from "@/hooks/use-resources";
import { resolveAssignments, type ResolvedAssignment, type ResourceData } from "@/services/resources";

export function BookingBadge({type}:{type:string}){return <span className={type==="Hard"?"rounded-full bg-primary/15 px-2 py-1 text-xs font-semibold text-primary":"rounded-full bg-health-warn/15 px-2 py-1 text-xs font-semibold text-health-warn-foreground"}>{type}</span>}
export function ResourceAssignments(){const query=useResourceData();return <QueryState query={query}>{data=><Assignments data={data}/>}</QueryState>}
function Assignments({data}:{data:ResourceData}){const all=useMemo(()=>resolveAssignments(data),[data]),[team,setTeam]=useState(""),[project,setProject]=useState(""),[programme,setProgramme]=useState(""),[booking,setBooking]=useState(""),[collapsed,setCollapsed]=useState<string[]>([]);const rows=useMemo(()=>all.filter(item=>(!team||item.team===team)&&(!project||item.projectId===project)&&(!programme||item.programmeId===programme)&&(!booking||item.bookingType===booking)),[all,team,project,programme,booking]);const groups=Array.from(new Set(rows.map(item=>item.resourceName)));const selectClass="h-9 rounded-md border bg-background px-3 text-xs";return <div className="space-y-4"><div className="flex flex-wrap gap-2 rounded-lg border border-border/70 bg-card p-3"><select aria-label="Team filter" value={team} onChange={event=>setTeam(event.target.value)} className={selectClass}><option value="">All teams</option>{Array.from(new Set(all.map(item=>item.team))).map(item=><option key={item}>{item}</option>)}</select><select aria-label="Programme filter" value={programme} onChange={event=>setProgramme(event.target.value)} className={selectClass}><option value="">All programmes</option>{data.programmes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Project filter" value={project} onChange={event=>setProject(event.target.value)} className={selectClass}><option value="">All projects</option>{data.projects.filter(item=>!programme||item.programmeId===programme).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Booking type filter" value={booking} onChange={event=>setBooking(event.target.value)} className={selectClass}><option value="">All bookings</option>{["Soft","Hard"].map(item=><option key={item}>{item}</option>)}</select></div><div className="overflow-hidden rounded-lg border border-border/70 bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead className="sticky top-0 bg-table-head"><tr>{["Resource / Project / Task","Start","Finish","Booking","Progress","Effort","Completed","Remaining"].map(item=><th key={item} className="border-b px-4 py-3 text-xs font-semibold text-muted-foreground">{item}</th>)}</tr></thead><tbody>{groups.map(group=>{const items=rows.filter(item=>item.resourceName===group),closed=collapsed.includes(group),total=items.reduce((sum,item)=>sum+item.effort,0);return <ResourceGroup key={group} name={group} closed={closed} toggle={()=>setCollapsed(current=>closed?current.filter(item=>item!==group):[...current,group])} items={items} total={total}/>})}</tbody></table></div></div></div>}
function ResourceGroup({name,closed,toggle,items,total}:{name:string;closed:boolean;toggle:()=>void;items:ResolvedAssignment[];total:number}){return <>{<tr className="bg-accent/45"><td colSpan={8}><button onClick={toggle} className="flex w-full items-center gap-2 px-4 py-3 text-left text-sm font-semibold">{closed?<ChevronRight className="size-4"/>:<ChevronDown className="size-4"/>}{name}<span className="text-xs font-normal text-muted-foreground">{items.length} assignments · {total}h</span></button></td></tr>}{!closed&&items.map(item=><tr key={item.id} className="border-b last:border-0"><td className="px-4 py-3"><p className="text-sm font-medium">{item.projectName}</p><p className="text-xs text-muted-foreground">{item.taskName??item.role}</p></td><td className="px-4 py-3 text-xs">{formatDate(item.start)}</td><td className="px-4 py-3 text-xs">{formatDate(item.end)}</td><td className="px-4 py-3"><BookingBadge type={item.bookingType}/></td><td className="px-4 py-3"><div className="w-28"><Progress value={item.progress}/><span className="text-[10px] text-muted-foreground">{item.progress}%</span></div></td><td className="px-4 py-3 text-sm">{item.effort}h</td><td className="px-4 py-3 text-sm">{item.effortCompleted}h</td><td className="px-4 py-3 text-sm font-semibold">{item.effortRemaining}h</td></tr>)}</>}