/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesProgrammeIdRouteImport } from './routes/programmes.$programmeId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesProgrammeIdRoute = ProgrammesProgrammeIdRouteImport.update({
  id: '/$programmeId',
  path: '/$programmeId',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/my-work': typeof MyWorkRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/resources': typeof ResourcesRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/my-work': typeof MyWorkRoute
  '/requests': typeof RequestsRoute
  '/resources': typeof ResourcesRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/my-work': typeof MyWorkRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/resources': typeof ResourcesRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/my-work'
    | '/programmes'
    | '/projects'
    | '/requests'
    | '/resources'
    | '/programmes/$programmeId'
    | '/programmes/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/my-work'
    | '/requests'
    | '/resources'
    | '/programmes/$programmeId'
    | '/programmes'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/my-work'
    | '/programmes'
    | '/projects'
    | '/requests'
    | '/resources'
    | '/programmes/$programmeId'
    | '/programmes/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  MyWorkRoute: typeof MyWorkRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RequestsRoute: typeof RequestsRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/$programmeId': {
      id: '/programmes/$programmeId'
      path: '/$programmeId'
      fullPath: '/programmes/$programmeId'
      preLoaderRoute: typeof ProgrammesProgrammeIdRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProgrammesRouteChildren {
  ProgrammesProgrammeIdRoute: typeof ProgrammesProgrammeIdRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesProgrammeIdRoute: ProgrammesProgrammeIdRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  MyWorkRoute: MyWorkRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RequestsRoute: RequestsRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
