/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as MyTimelineRouteImport } from './routes/my-timeline'
import { Route as MyWorkRouteImport } from './routes/my-work'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResourceAllocationRouteImport } from './routes/resource-allocation'
import { Route as ResourceAssignmentsRouteImport } from './routes/resource-assignments'
import { Route as ResourceScenariosRouteImport } from './routes/resource-scenarios'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as TaskOverviewRouteImport } from './routes/task-overview'
import { Route as BenefitsIndexRouteImport } from './routes/benefits.index'
import { Route as BenefitsBenefitIdRouteImport } from './routes/benefits.$benefitId'
import { Route as BenefitsDashboardRouteImport } from './routes/benefits.dashboard'
import { Route as BenefitsMapRouteImport } from './routes/benefits.map'
import { Route as BenefitsRealisationRouteImport } from './routes/benefits.realisation'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesProgrammeIdRouteImport } from './routes/programmes.$programmeId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTimelineRoute = MyTimelineRouteImport.update({
  id: '/my-timeline',
  path: '/my-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorkRoute = MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceAllocationRoute = ResourceAllocationRouteImport.update({
  id: '/resource-allocation',
  path: '/resource-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceAssignmentsRoute = ResourceAssignmentsRouteImport.update({
  id: '/resource-assignments',
  path: '/resource-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceScenariosRoute = ResourceScenariosRouteImport.update({
  id: '/resource-scenarios',
  path: '/resource-scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskOverviewRoute = TaskOverviewRouteImport.update({
  id: '/task-overview',
  path: '/task-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIndexRoute = BenefitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BenefitsRoute,
} as any)
const BenefitsBenefitIdRoute = BenefitsBenefitIdRouteImport.update({
  id: '/$benefitId',
  path: '/$benefitId',
  getParentRoute: () => BenefitsRoute,
} as any)
const BenefitsDashboardRoute = BenefitsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BenefitsRoute,
} as any)
const BenefitsMapRoute = BenefitsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => BenefitsRoute,
} as any)
const BenefitsRealisationRoute = BenefitsRealisationRouteImport.update({
  id: '/realisation',
  path: '/realisation',
  getParentRoute: () => BenefitsRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesProgrammeIdRoute = ProgrammesProgrammeIdRouteImport.update({
  id: '/$programmeId',
  path: '/$programmeId',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benefits': typeof BenefitsRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboards': typeof DashboardsRoute
  '/milestones': typeof MilestonesRoute
  '/my-timeline': typeof MyTimelineRoute
  '/my-work': typeof MyWorkRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/resource-allocation': typeof ResourceAllocationRoute
  '/resource-assignments': typeof ResourceAssignmentsRoute
  '/resource-scenarios': typeof ResourceScenariosRoute
  '/resources': typeof ResourcesRoute
  '/risks': typeof RisksRoute
  '/roadmaps': typeof RoadmapsRoute
  '/task-overview': typeof TaskOverviewRoute
  '/benefits/$benefitId': typeof BenefitsBenefitIdRoute
  '/benefits/dashboard': typeof BenefitsDashboardRoute
  '/benefits/map': typeof BenefitsMapRoute
  '/benefits/realisation': typeof BenefitsRealisationRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/milestones': typeof MilestonesRoute
  '/my-timeline': typeof MyTimelineRoute
  '/my-work': typeof MyWorkRoute
  '/requests': typeof RequestsRoute
  '/resource-allocation': typeof ResourceAllocationRoute
  '/resource-assignments': typeof ResourceAssignmentsRoute
  '/resource-scenarios': typeof ResourceScenariosRoute
  '/resources': typeof ResourcesRoute
  '/risks': typeof RisksRoute
  '/roadmaps': typeof RoadmapsRoute
  '/task-overview': typeof TaskOverviewRoute
  '/benefits/$benefitId': typeof BenefitsBenefitIdRoute
  '/benefits/dashboard': typeof BenefitsDashboardRoute
  '/benefits/map': typeof BenefitsMapRoute
  '/benefits/realisation': typeof BenefitsRealisationRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/benefits': typeof BenefitsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benefits': typeof BenefitsRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboards': typeof DashboardsRoute
  '/milestones': typeof MilestonesRoute
  '/my-timeline': typeof MyTimelineRoute
  '/my-work': typeof MyWorkRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/resource-allocation': typeof ResourceAllocationRoute
  '/resource-assignments': typeof ResourceAssignmentsRoute
  '/resource-scenarios': typeof ResourceScenariosRoute
  '/resources': typeof ResourcesRoute
  '/risks': typeof RisksRoute
  '/roadmaps': typeof RoadmapsRoute
  '/task-overview': typeof TaskOverviewRoute
  '/benefits/$benefitId': typeof BenefitsBenefitIdRoute
  '/benefits/dashboard': typeof BenefitsDashboardRoute
  '/benefits/map': typeof BenefitsMapRoute
  '/benefits/realisation': typeof BenefitsRealisationRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/programmes/$programmeId': typeof ProgrammesProgrammeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benefits'
    | '/collections'
    | '/dashboards'
    | '/milestones'
    | '/my-timeline'
    | '/my-work'
    | '/programmes'
    | '/projects'
    | '/requests'
    | '/resource-allocation'
    | '/resource-assignments'
    | '/resource-scenarios'
    | '/resources'
    | '/risks'
    | '/roadmaps'
    | '/task-overview'
    | '/benefits/$benefitId'
    | '/benefits/dashboard'
    | '/benefits/map'
    | '/benefits/realisation'
    | '/collections/$collectionId'
    | '/programmes/$programmeId'
    | '/projects/$projectId'
    | '/benefits/'
    | '/collections/'
    | '/programmes/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards'
    | '/milestones'
    | '/my-timeline'
    | '/my-work'
    | '/requests'
    | '/resource-allocation'
    | '/resource-assignments'
    | '/resource-scenarios'
    | '/resources'
    | '/risks'
    | '/roadmaps'
    | '/task-overview'
    | '/benefits/$benefitId'
    | '/benefits/dashboard'
    | '/benefits/map'
    | '/benefits/realisation'
    | '/collections/$collectionId'
    | '/programmes/$programmeId'
    | '/projects/$projectId'
    | '/benefits'
    | '/collections'
    | '/programmes'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/benefits'
    | '/collections'
    | '/dashboards'
    | '/milestones'
    | '/my-timeline'
    | '/my-work'
    | '/programmes'
    | '/projects'
    | '/requests'
    | '/resource-allocation'
    | '/resource-assignments'
    | '/resource-scenarios'
    | '/resources'
    | '/risks'
    | '/roadmaps'
    | '/task-overview'
    | '/benefits/$benefitId'
    | '/benefits/dashboard'
    | '/benefits/map'
    | '/benefits/realisation'
    | '/collections/$collectionId'
    | '/programmes/$programmeId'
    | '/projects/$projectId'
    | '/benefits/'
    | '/collections/'
    | '/programmes/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenefitsRoute: typeof BenefitsRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DashboardsRoute: typeof DashboardsRoute
  MilestonesRoute: typeof MilestonesRoute
  MyTimelineRoute: typeof MyTimelineRoute
  MyWorkRoute: typeof MyWorkRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RequestsRoute: typeof RequestsRoute
  ResourceAllocationRoute: typeof ResourceAllocationRoute
  ResourceAssignmentsRoute: typeof ResourceAssignmentsRoute
  ResourceScenariosRoute: typeof ResourceScenariosRoute
  ResourcesRoute: typeof ResourcesRoute
  RisksRoute: typeof RisksRoute
  RoadmapsRoute: typeof RoadmapsRoute
  TaskOverviewRoute: typeof TaskOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-timeline': {
      id: '/my-timeline'
      path: '/my-timeline'
      fullPath: '/my-timeline'
      preLoaderRoute: typeof MyTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-work': {
      id: '/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof MyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-allocation': {
      id: '/resource-allocation'
      path: '/resource-allocation'
      fullPath: '/resource-allocation'
      preLoaderRoute: typeof ResourceAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-assignments': {
      id: '/resource-assignments'
      path: '/resource-assignments'
      fullPath: '/resource-assignments'
      preLoaderRoute: typeof ResourceAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-scenarios': {
      id: '/resource-scenarios'
      path: '/resource-scenarios'
      fullPath: '/resource-scenarios'
      preLoaderRoute: typeof ResourceScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-overview': {
      id: '/task-overview'
      path: '/task-overview'
      fullPath: '/task-overview'
      preLoaderRoute: typeof TaskOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/': {
      id: '/benefits/'
      path: '/'
      fullPath: '/benefits/'
      preLoaderRoute: typeof BenefitsIndexRouteImport
      parentRoute: typeof BenefitsRoute
    }
    '/benefits/$benefitId': {
      id: '/benefits/$benefitId'
      path: '/$benefitId'
      fullPath: '/benefits/$benefitId'
      preLoaderRoute: typeof BenefitsBenefitIdRouteImport
      parentRoute: typeof BenefitsRoute
    }
    '/benefits/dashboard': {
      id: '/benefits/dashboard'
      path: '/dashboard'
      fullPath: '/benefits/dashboard'
      preLoaderRoute: typeof BenefitsDashboardRouteImport
      parentRoute: typeof BenefitsRoute
    }
    '/benefits/map': {
      id: '/benefits/map'
      path: '/map'
      fullPath: '/benefits/map'
      preLoaderRoute: typeof BenefitsMapRouteImport
      parentRoute: typeof BenefitsRoute
    }
    '/benefits/realisation': {
      id: '/benefits/realisation'
      path: '/realisation'
      fullPath: '/benefits/realisation'
      preLoaderRoute: typeof BenefitsRealisationRouteImport
      parentRoute: typeof BenefitsRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/$programmeId': {
      id: '/programmes/$programmeId'
      path: '/$programmeId'
      fullPath: '/programmes/$programmeId'
      preLoaderRoute: typeof ProgrammesProgrammeIdRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface BenefitsRouteChildren {
  BenefitsBenefitIdRoute: typeof BenefitsBenefitIdRoute
  BenefitsDashboardRoute: typeof BenefitsDashboardRoute
  BenefitsMapRoute: typeof BenefitsMapRoute
  BenefitsRealisationRoute: typeof BenefitsRealisationRoute
  BenefitsIndexRoute: typeof BenefitsIndexRoute
}

const BenefitsRouteChildren: BenefitsRouteChildren = {
  BenefitsBenefitIdRoute: BenefitsBenefitIdRoute,
  BenefitsDashboardRoute: BenefitsDashboardRoute,
  BenefitsMapRoute: BenefitsMapRoute,
  BenefitsRealisationRoute: BenefitsRealisationRoute,
  BenefitsIndexRoute: BenefitsIndexRoute,
}

const BenefitsRouteWithChildren = BenefitsRoute._addFileChildren(
  BenefitsRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface ProgrammesRouteChildren {
  ProgrammesProgrammeIdRoute: typeof ProgrammesProgrammeIdRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesProgrammeIdRoute: ProgrammesProgrammeIdRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenefitsRoute: BenefitsRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  DashboardsRoute: DashboardsRoute,
  MilestonesRoute: MilestonesRoute,
  MyTimelineRoute: MyTimelineRoute,
  MyWorkRoute: MyWorkRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RequestsRoute: RequestsRoute,
  ResourceAllocationRoute: ResourceAllocationRoute,
  ResourceAssignmentsRoute: ResourceAssignmentsRoute,
  ResourceScenariosRoute: ResourceScenariosRoute,
  ResourcesRoute: ResourcesRoute,
  RisksRoute: RisksRoute,
  RoadmapsRoute: RoadmapsRoute,
  TaskOverviewRoute: TaskOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
